refactor to decrease number of workflows

diff --git a/.github/workflows/test_cli_misc.yaml b/.github/workflows/test_cli_misc.yaml
--- a/.github/workflows/test_cli_misc.yaml
+++ b/.github/workflows/test_cli_misc.yaml
@@ -68,4 +68,10 @@ jobs:
       - name: Run tests from example folder
         run: |
           pytest tests/test_examples_folder.py -s -k "examples and not (cpu or cuda or rocm or mps)"
-        continue-on-error: ${{ failure() && steps.run.outcome == 'failure' && steps.run.exit_code == 5 }}
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -eq 5 ]; then
+            echo "No tests were collected. Skipping failure..."
+            exit 0
+          else
+            exit $EXIT_CODE
+          fi
